CREATE DATABASE C2514_DB;
CREATE TABLE ORDERS ( OrderID INT PRIMARY KEY, CustomerID INT, OrderTime DATETIME, ProductName VARCHAR(50), FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID) );
ALTER TABLE CUSTOMERS AUTO_INCREMENT = 1;
DROP DATABASE C2514_DB;
USE C2514_DB;
CREATE TABLE CUSTOMERS ( CustomerID INT AUTO_INCREMENT PRIMARY KEY, FirstName VARCHAR(50), LastName VARCHAR(50), Gender CHAR(1), PhoneNumber VARCHAR(15) );
CREATE TABLE IF NOT EXISTS ORDERS ( OrderID INT AUTO_INCREMENT PRIMARY KEY, CustomerID INT, ProductID INT, OrderDate DATETIME, FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID) );
SHOW COLUMNS FROM orders;
ALTER TABLE orders ADD COLUMN product_id INT;
SELECT FirstName, PhoneNumber FROM CUSTOMERS WHERE Gender = 'F' AND LastName = 'Bluth';
SELECT COUNT(*) AS MaleWithoutPhone FROM CUSTOMERS WHERE Gender = 'M' AND PhoneNumber IS NULL;
CREATE TABLE IF NOT EXISTS PRODUCTS ( ProductID INT AUTO_INCREMENT PRIMARY KEY, ProductName VARCHAR(50), Origin VARCHAR(50), Price DECIMAL(10, 2) );
INSERT INTO PRODUCTS (ProductName, Origin, Price) VALUES ('Cappuccino', 'Italy', 3.50), ('Espresso', 'Italy', 2.00), ('Latte', 'India', 3.00), ('Mocha', 'Indonesia', 4.00), ('Americano', 'USA', 2.50);
SELECT ProductName FROM PRODUCTS WHERE Origin IN ('India', 'Indonesia');
SELECT * FROM `customers`
SELECT CUSTOMERS.FirstName, CUSTOMERS.LastName, ORDERS.OrderDate FROM CUSTOMERS JOIN ORDERS ON CUSTOMERS.CustomerID = ORDERS.CustomerID JOIN PRODUCTS ON ORDERS.ProductID = PRODUCTS.ProductID WHERE PRODUCTS.ProductName = 'Cappuccino';
SELECT CUSTOMERS.FirstName, CUSTOMERS.LastName, PRODUCTS.ProductName FROM CUSTOMERS JOIN ORDERS ON CUSTOMERS.CustomerID = ORDERS.CustomerID JOIN PRODUCTS ON ORDERS.ProductID = PRODUCTS.ProductID;
CREATE TABLE Orders_1NF ( OrderID INT, CustomerName VARCHAR(50), ProductName VARCHAR(50) );
SELECT * FROM `customers`
CREATE TABLE StudentCourses ( StudentID INT, CourseID INT, PRIMARY KEY (StudentID, CourseID), FOREIGN KEY (StudentID) REFERENCES Students(StudentID), FOREIGN KEY (CourseID) REFERENCES Courses(CourseID) );
CREATE TABLE Sales ( SalesID INT PRIMARY KEY, ProductID INT, SaleDate DATE);
CREATE TABLE BookAuthors ( BookID INT, AuthorID INT );
Expand Requery Edit Database : Queried time : 4:36:17
CREATE TABLE Orders2 ( OrderID INT PRIMARY KEY, ProductID INT );