CREATE TABLE room_assignments ( assignment_id INT PRIMARY KEY AUTO_INCREMENT, staff_id INT, room_id INT, task_description VARCHAR(100), assignment_date DATE NOT NULL, FOREIGN KEY (staff_id) REFERENCES staff(staff_id) ON DELETE CASCADE, FOREIGN KEY (room_id) REFERENCES rooms(room_id) ON DELETE CASCADE );
INSERT INTO room_assignments (staff_id, room_id, task_description, assignment_date) VALUES (1, 1, 'cleaning', '2024-11-01'), (2, 3, 'maintenance', '2024-11-05'), (3, 2, 'managing reservation', '2024-10-30'), (4, 5, 'cleaning', '2024-11-20'), (5, 4, 'maintenance', '2024-11-10');
SELECT * FROM rooms WHERE floor = 1 AND status = 'available';
SELECT r.reservation_id, c.first_name, c.last_name, c.email, r.check_in, r.check_out FROM reservations r JOIN customers c ON r.customer_id = c.customer_id ORDER BY r.check_in ASC;
SELECT c.first_name, c.last_name, c.email, DATEDIFF(r.check_out, r.check_in) AS nights FROM reservations r JOIN customers c ON r.customer_id = c.customer_id WHERE DATEDIFF(r.check_out, r.check_in) > 5;
SELECT c.first_name, c.last_name, c.email, DATEDIFF(r.check_out, r.check_in) AS nights FROM reservations r JOIN customers c ON r.customer_id = c.customer_id WHERE DATEDIFF(r.check_out, r.check_in) > 5;
SELECT c.first_name, c.last_name, c.email, DATEDIFF(r.check_out, r.check_in) AS nights FROM reservations r JOIN customers c ON r.customer_id = c.customer_id WHERE DATEDIFF(r.check_out, r.check_in) > 5;
SELECT r.reservation_id, SUM(p.amount) AS total_paid FROM payments p JOIN reservations r ON p.reservation_id = r.reservation_id GROUP BY r.reservation_id;
SELECT SUM(p.amount) AS total_revenue FROM payments p JOIN reservations r ON p.reservation_id = r.reservation_id WHERE r.reservation_date >= CURDATE() - INTERVAL 1 MONTH;
SELECT room_type, AVG(price) AS average_price FROM rooms GROUP BY room_type;
SELECT * FROM rooms r WHERE NOT EXISTS ( SELECT 1 FROM reservations res WHERE res.room_id = r.room_id AND res.check_in <= '2024-11-10' AND res.check_out >= '2024-11-05' );
SELECT s.staff_name, COUNT(ra.assignment_id) AS assignments FROM staff s JOIN room_assignments ra ON s.staff_id = ra.staff_id WHERE ra.task_description IN ('cleaning', 'maintenance') AND ra.assignment_date >= CURDATE() - INTERVAL 1 MONTH GROUP BY s.staff_name ORDER BY assignments DESC LIMIT 1;
SELECT c.first_name, c.last_name, c.email, r.reservation_date FROM customers c JOIN reservations r ON c.customer_id = r.customer_id WHERE r.reservation_date = ( SELECT MAX(reservation_date) FROM reservations WHERE customer_id = c.customer_id );
DELETE FROM reservations WHERE reservation_id = 1;
DELETE FROM reservations WHERE reservation_id = 1;
DELETE FROM reservations WHERE reservation_id = 1;
DESCRIBE customers;
SELECT * FROM customers LIMIT 5;
DESCRIBE customers;